### ISSUE TITLE
Authorize Net URL updates

### ISSUE THREAD

**Issue by sean-hill** [durango/authorize-net-request#7]
Authorize.net recently sent out an email saying they are updating their URL's as stated here:

## Updating Your Solution

The new Akamai transaction URLs that are available now are:

`https://api2.authorize.net/xml/v1/request.api`
`https://api2.authorize.net/soap/v1/Service.asmx`
`https://secure2.authorize.net/gateway/transact.dll`

We will begin sending our initial emails about Akamai to merchants starting tomorrow.

Could this repo be updated to reflect those changes? Thanks!

**Comment by durango** [comment]
Did Authorize.net say anything about their `apitest` server/namespace?

**Comment by durango** [comment]
Anything else? https://github.com/durango/authorize-net-request/pull/8

**Comment by thgaskell** [comment]
@durango I contacted their support team regarding `apitest`:

    Please note that our sandbox URLs will not change because our sandbox environment is already on Akamai.

Should be good to merge :+1:

**Comment by durango** [comment]
Thanks, pushed to npm! (Forgot to update this)

**Comment by sean-hill** [comment]
:thumbsup:

**Comment by sean-hill** [comment]
Oh wait, is this change reflected in the auth-net-cim repo also? Since this is a dependency.

**Comment by sean-hill** [comment]
Forget I asked that :) Thanks for the quick fix!
