### ISSUE TITLE
Special Request

### ISSUE THREAD

**Issue by sean-hill** [durango/authorize-net-request#9]
Hey there,

I'm trying to create a new customer profile. The description I'm passing in is `Manuel Meléndez customer account`, however I get this error from authorize.net: `Authorize.net error: Unexpected end of file has occurred. The following elements are not closed: createCustomerProfileRequest. Line 1, position 380.`. I debugged it and the `é` is what is causing the problem. I asked authorize.net about it and this was there response: 

You should be able to pass any character from the ISO-8859-1 character set as long as this character set is properly defined in the XML itself. We were able to test this successfully using the XML header of: `<?xml version="1.0" encoding="ISO-8859-1"?>`

Does this repo need to be updated to fix this problem?

**Comment by sean-hill** [comment]
Looks like this repo has `encoding` set to `utf-8`.

**Comment by sean-hill** [comment]
I created a pull request to fix this issue [here](https://github.com/durango/authorize-net-request/pull/10).

**Comment by sean-hill** [comment]
Also could the `auth-net-cim` repo dependency be updated? Thanks.

**Comment by durango** [comment]
@sean-hill thanks for the PR! Sorry for the troubles.

**Comment by durango** [comment]
@sean-hill yup was just about to

**Comment by sean-hill** [comment]
You rock, and no worries! :shipit:

**Comment by durango** [comment]
@sean-hill done, thanks again for taking care of that
